/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Donation } from "./Donation";

export { Donation__factory } from "./factories/Donation__factory";
